FROM python:3.9-slim

ENV PUID=1000
ENV PGID=1000

RUN apt-get update && apt-get install -y \
    espeak \
    libespeak-dev \
    libsndfile1 \
    ffmpeg \
    libmagic-dev \
    build-essential \
    python3-dev \
    gcc \
    jq \
    curl \
    && apt-get clean

RUN pip install --upgrade pip

RUN pip install numpy \
    && pip install aeneas \
    && pip install Flask

# Create user and set ownership with environment variables
RUN groupadd -g ${PGID} appgroup && \
    useradd -u ${PUID} -g appgroup appuser

COPY process_subtitles.py /aeneas/process_subtitles.py
COPY app.py /aeneas/app.py

WORKDIR /aeneas

# Set proper ownership using environment variables
RUN chown -R ${PUID}:${PGID} /aeneas

USER ${PUID}:${PGID}

EXPOSE 5000

ENTRYPOINT ["python", "/aeneas/app.py"]
